### ISSUE TITLE
two examples

### ISSUE THREAD

**Issue by davidgohel** [duperrex/questions_in_R#1]
I left two examples, one with bookdown, one with only rmarkdown.

Two templates:
- if rmarkdown, titles and caption styles should be numbered in template
- if bookdown, titles and caption styles should not be numbered in template as bookdown will prepend numbers to them in the doc

**Comment by duperrex** [comment]
Thanks a lot for the files and the clarifications. Works perfectly. I'll answer the [question in SO](https://stackoverflow.com/q/73936465/6176250).
